# Generated by Django 3.0.3 on 2020-03-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('idAyuda', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('nombreImg', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCiudad', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('idInstitucion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreInstitucion', models.CharField(max_length=240)),
                ('correoInstitucion', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('idNosotros', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcionNosotros', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePais', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
