# Generated by Django 3.0.3 on 2020-03-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelControl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='urlImg',
            field=models.CharField(default='ejemplo.png', max_length=100),
            preserve_default=False,
        ),
    ]
