# Generated by Django 3.0.3 on 2020-03-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelControl', '0002_persona_urlimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion_Nosotros', models.CharField(max_length=240)),
                ('Descripcion_Ayuda', models.CharField(max_length=240)),
                ('Pais', models.CharField(max_length=240)),
                ('Ciudad', models.CharField(max_length=240)),
            ],
        ),
        migrations.RenameModel(
            old_name='Persona',
            new_name='Equipo',
        ),
        migrations.DeleteModel(
            name='Ayuda',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Nosotros',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
