# Generated by Django 3.0.3 on 2020-03-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelControl', '0005_auto_20200310_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
