# Generated by Django 3.0.3 on 2020-03-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelControl', '0006_auto_20200310_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Descripcion_Ayuda',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Descripcion_Nosotros',
            field=models.CharField(max_length=500),
        ),
    ]
